// Mocks generated by Mockito 5.4.6 from annotations
// in rick_morty/test/presentation/viewmodels/favorites_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_morty/domain/entities/character.dart' as _i5;
import 'package:rick_morty/domain/entities/characters_page.dart' as _i2;
import 'package:rick_morty/domain/repositories/character_repository.dart'
    as _i3;
import 'package:rick_morty/domain/repositories/favorites_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharactersPage_0 extends _i1.SmartFake
    implements _i2.CharactersPage {
  _FakeCharactersPage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CharacterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRepository extends _i1.Mock
    implements _i3.CharacterRepository {
  MockCharacterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CharactersPage> getCharacters({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacters, [], {#page: page}),
            returnValue: _i4.Future<_i2.CharactersPage>.value(
              _FakeCharactersPage_0(
                this,
                Invocation.method(#getCharacters, [], {#page: page}),
              ),
            ),
          )
          as _i4.Future<_i2.CharactersPage>);

  @override
  _i4.Future<_i5.Character?> getCharacterById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacterById, [id]),
            returnValue: _i4.Future<_i5.Character?>.value(),
          )
          as _i4.Future<_i5.Character?>);

  @override
  _i4.Future<List<_i5.Character>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getCharactersByIds, [ids]),
            returnValue: _i4.Future<List<_i5.Character>>.value(
              <_i5.Character>[],
            ),
          )
          as _i4.Future<List<_i5.Character>>);

  @override
  _i4.Future<_i2.CharactersPage> searchCharacters({
    required String? name,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchCharacters, [], {
              #name: name,
              #page: page,
            }),
            returnValue: _i4.Future<_i2.CharactersPage>.value(
              _FakeCharactersPage_0(
                this,
                Invocation.method(#searchCharacters, [], {
                  #name: name,
                  #page: page,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.CharactersPage>);
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i6.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<int>> getFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIds, []),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<void> addToFavorites(int? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#addToFavorites, [characterId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromFavorites(int? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavorites, [characterId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isFavorite(int? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [characterId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#clearFavorites, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
