// Mocks generated by Mockito 5.4.4 from annotations
// in rick_morty/test/data/repositories/character_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_morty/data/datasources/character_local_datasource.dart'
    as _i6;
import 'package:rick_morty/data/datasources/character_remote_datasource.dart'
    as _i4;
import 'package:rick_morty/data/models/character_model.dart' as _i3;
import 'package:rick_morty/data/models/characters_response.dart' as _i2;
import 'package:rick_morty/domain/entities/character.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharactersResponse_0 extends _i1.SmartFake
    implements _i2.CharactersResponse {
  _FakeCharactersResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacterModel_1 extends _i1.SmartFake
    implements _i3.CharacterModel {
  _FakeCharacterModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CharacterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRemoteDataSource extends _i1.Mock
    implements _i4.CharacterRemoteDataSource {
  MockCharacterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CharactersResponse> getCharacters({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [],
          {#page: page},
        ),
        returnValue:
            _i5.Future<_i2.CharactersResponse>.value(_FakeCharactersResponse_0(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {#page: page},
          ),
        )),
      ) as _i5.Future<_i2.CharactersResponse>);

  @override
  _i5.Future<_i3.CharacterModel> getCharacterById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterById,
          [id],
        ),
        returnValue: _i5.Future<_i3.CharacterModel>.value(_FakeCharacterModel_1(
          this,
          Invocation.method(
            #getCharacterById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.CharacterModel>);

  @override
  _i5.Future<List<_i3.CharacterModel>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByIds,
          [ids],
        ),
        returnValue:
            _i5.Future<List<_i3.CharacterModel>>.value(<_i3.CharacterModel>[]),
      ) as _i5.Future<List<_i3.CharacterModel>>);

  @override
  _i5.Future<_i2.CharactersResponse> searchCharacters({
    required String? name,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCharacters,
          [],
          {
            #name: name,
            #page: page,
          },
        ),
        returnValue:
            _i5.Future<_i2.CharactersResponse>.value(_FakeCharactersResponse_0(
          this,
          Invocation.method(
            #searchCharacters,
            [],
            {
              #name: name,
              #page: page,
            },
          ),
        )),
      ) as _i5.Future<_i2.CharactersResponse>);
}

/// A class which mocks [CharacterLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterLocalDataSource extends _i1.Mock
    implements _i6.CharacterLocalDataSource {
  MockCharacterLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheCharacters(List<_i7.Character>? characters) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCharacters,
          [characters],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cacheCharacter(_i7.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCharacter,
          [character],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Character?> getCachedCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCachedCharacter,
          [id],
        ),
        returnValue: _i5.Future<_i7.Character?>.value(),
      ) as _i5.Future<_i7.Character?>);

  @override
  _i5.Future<List<_i7.Character>> getAllCachedCharacters() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCachedCharacters,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Character>>.value(<_i7.Character>[]),
      ) as _i5.Future<List<_i7.Character>>);

  @override
  _i5.Future<List<_i7.Character>> getCachedCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedCharactersByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i7.Character>>.value(<_i7.Character>[]),
      ) as _i5.Future<List<_i7.Character>>);

  @override
  _i5.Future<List<_i7.Character>> searchCachedCharacters(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCachedCharacters,
          [query],
        ),
        returnValue: _i5.Future<List<_i7.Character>>.value(<_i7.Character>[]),
      ) as _i5.Future<List<_i7.Character>>);

  @override
  _i5.Future<bool> hasCachedData() => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupStaleCache() => (super.noSuchMethod(
        Invocation.method(
          #cleanupStaleCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
